[package]
name = "device"
version = "0.1.0"
edition = "2021"

[dependencies]
simple-network = {path = "../simple-network"}
tokio = {version = "1.34.0", features = ["full"] }
bytes = "1.5.0"
anyhow = "1.0.75"