
[package]
name = "simple-network"
version = "0.1.0"
edition = "2021"


[dependencies]
async-trait = "0.1.81"
bytes = "1.6.1"
bytebuffer = "2.2.0"
anyhow = "1.0.86"
tokio = {version = "1.39.2", features = ["full"] }
scopeguard = "1.2.0"